-- Listando as ocorrências de atividade
SELECT 
    A.NOME AS ATIVIDADE,
    I.NOME AS LOCAL,
    I.TIPO AS TIPO_LOCAL,
    O.DIA_SEMANA,
    O.HORARIO_INICIO,
    O.HORARIO_FIM,
    P.NOME AS EDUCADOR_RESPONSAVEL
FROM ATIVIDADE A
INNER JOIN OCORRENCIA_SEMANAL O ON A.ID_ATIVIDADE = O.ID_ATIVIDADE
INNER JOIN INSTALACAO I ON O.ID_INSTALACAO = I.ID_INSTALACAO
INNER JOIN CONDUZ_ATIVIDADE CA ON A.ID_ATIVIDADE = CA.ID_ATIVIDADE
INNER JOIN EDUCADOR_FISICO EF ON CA.CPF_EDUCADOR_FISICO = EF.CPF_FUNCIONARIO
INNER JOIN PESSOA P ON EF.CPF_FUNCIONARIO = P.CPF
ORDER BY O.DIA_SEMANA, O.HORARIO_INICIO;

-- Instalações mais reservadas
SELECT
    I.NOME,
    I.TIPO,
    COUNT(R.ID_RESERVA) AS TOTAL_RESERVAS
FROM INSTALACAO I
LEFT JOIN RESERVA R ON I.ID_INSTALACAO = R.ID_INSTALACAO
WHERE I.EH_RESERVAVEL = 'S'
GROUP BY I.ID_INSTALACAO, I.NOME, I.TIPO
ORDER BY TOTAL_RESERVAS DESC;

-- Participantes externos e seus anfitriões
SELECT
    P_PARTICIPANTE.NOME AS PARTICIPANTE_EXTERNO,
    P_PARTICIPANTE.EMAIL AS EMAIL_PARTICIPANTE,
    A.NOME AS ATIVIDADE,
    P_CONVIDANTE.NOME AS ANFITRIAO_USP,
    IU.NUSP AS NUSP_ANFITRIAO
FROM PARTICIPACAO_ATIVIDADE PA
INNER JOIN PESSOA P_PARTICIPANTE ON PA.CPF_PARTICIPANTE = P_PARTICIPANTE.CPF
INNER JOIN ATIVIDADE A ON PA.ID_ATIVIDADE = A.ID_ATIVIDADE
INNER JOIN INTERNO_USP IU ON PA.CPF_CONVIDANTE_INTERNO = IU.CPF_PESSOA
INNER JOIN PESSOA P_CONVIDANTE ON IU.CPF_PESSOA = P_CONVIDANTE.CPF
LEFT JOIN INTERNO_USP IU_PARTICIPANTE ON PA.CPF_PARTICIPANTE = IU_PARTICIPANTE.CPF_PESSOA
WHERE
    IU_PARTICIPANTE.CPF_PESSOA IS NULL;