SELECT COUNT (*) AS TOTAL
  FROM PESSOA;

SELECT COUNT (*) AS TOTAL
  FROM INTERNO_USP;

SELECT COUNT (*) AS TOTAL
    FROM FUNCIONARIO;

SELECT COUNT (*) AS TOTAL
    FROM FUNCIONARIO_ATRIBUICAO;

SELECT COUNT (*) AS TOTAL
    FROM FUNCIONARIO_RESTRICAO;

SELECT COUNT (*) AS TOTAL
    FROM EDUCADOR_FISICO;

SELECT COUNT (*) AS TOTAL
    FROM INSTALACAO;

SELECT COUNT (*) AS TOTAL
    FROM EQUIPAMENTO;

SELECT COUNT (*) AS TOTAL
    FROM EQUIPAMENTO;

SELECT COUNT (*) AS TOTAL
    FROM DOACAO;

SELECT COUNT (*) AS TOTAL
    FROM RESERVA;

SELECT COUNT (*) AS TOTAL
    FROM ATIVIDADE;

SELECT COUNT (*) AS TOTAL
    FROM OCORRENCIA_SEMANAL;

SELECT COUNT (*) AS TOTAL
    FROM CONDUZ_ATIVIDADE;

SELECT COUNT (*) AS TOTAL
    FROM PARTICIPACAO_ATIVIDADE;

SELECT COUNT (*) AS TOTAL
    FROM EVENTO;

SELECT COUNT (*) AS TOTAL
    FROM SUPERVISAO_EVENTO;

SELECT COUNT (*) AS TOTAL
    FROM GRUPO_EXTENSAO;

SELECT COUNT (*) AS TOTAL
    FROM ATIVIDADE_GRUPO_EXTENSAO;