-- Drop tables in reverse order of creation from upgrade_schema.sql
-- Using CASCADE to ensure dependent objects (FKs, constraints) are removed.

DROP TABLE IF EXISTS SOLICITACAO_CADASTRO CASCADE;
DROP TABLE IF EXISTS USUARIO_SENHA CASCADE;
DROP TABLE IF EXISTS METRICA_ACESSO_DIARIA CASCADE;
DROP TABLE IF EXISTS AUDITORIA_LOGIN CASCADE;
DROP TABLE IF EXISTS EMPRESTIMO_EQUIPAMENTO CASCADE;
DROP TABLE IF EXISTS CONVITE_EXTERNO CASCADE;
DROP TABLE IF EXISTS RESERVA_EQUIPAMENTO CASCADE;
DROP TABLE IF EXISTS SUPERVISAO_EVENTO CASCADE;
DROP TABLE IF EXISTS CONDUZ_ATIVIDADE CASCADE;
DROP TABLE IF EXISTS PARTICIPACAO_ATIVIDADE CASCADE;
DROP TABLE IF EXISTS OCORRENCIA_SEMANAL CASCADE;
DROP TABLE IF EXISTS ATIVIDADE_GRUPO_EXTENSAO CASCADE;
DROP TABLE IF EXISTS GRUPO_EXTENSAO CASCADE;
DROP TABLE IF EXISTS EVENTO CASCADE;
DROP TABLE IF EXISTS RESERVA CASCADE;
DROP TABLE IF EXISTS DOACAO CASCADE;
DROP TABLE IF EXISTS EQUIPAMENTO CASCADE;
DROP TABLE IF EXISTS INSTALACAO CASCADE;
DROP TABLE IF EXISTS EDUCADOR_FISICO CASCADE;
DROP TABLE IF EXISTS FUNCIONARIO_RESTRICAO CASCADE;
DROP TABLE IF EXISTS FUNCIONARIO_ATRIBUICAO CASCADE;
DROP TABLE IF EXISTS FUNCIONARIO CASCADE;
DROP TABLE IF EXISTS INTERNO_USP CASCADE;
DROP TABLE IF EXISTS PESSOA CASCADE;
DROP TABLE IF EXISTS ATIVIDADE CASCADE;
DROP TYPE IF EXISTS DIA_SEMANA CASCADE;
