-- Insert test user with email teste@usp.br
-- This user should exist in PESSOA and INTERNO_USP tables
-- CPF: 12345678901 (test CPF)
-- Password: teste123 (will be hashed)

-- First, ensure the test user exists in PESSOA
INSERT INTO PESSOA (CPF, NOME, EMAIL, CELULAR, DATA_NASCIMENTO)
VALUES ('12345678901', 'Test User Admin', 'teste@usp.br', '(11) 99999-9999', '1990-01-01')
ON CONFLICT (CPF) DO UPDATE
SET EMAIL = EXCLUDED.EMAIL,
    NOME = EXCLUDED.NOME;

-- Ensure the test user exists in INTERNO_USP
INSERT INTO INTERNO_USP (CPF_PESSOA, NUSP, CATEGORIA)
VALUES ('12345678901', '1234567890', 'FUNCIONARIO')
ON CONFLICT (CPF_PESSOA) DO UPDATE
SET NUSP = EXCLUDED.NUSP;

-- Ensure the test user exists in FUNCIONARIO
INSERT INTO FUNCIONARIO (CPF_INTERNO, FORMACAO)
VALUES ('12345678901', 'Administração')
ON CONFLICT (CPF_INTERNO) DO NOTHING;

-- Ensure the test user has admin role
INSERT INTO FUNCIONARIO_ATRIBUICAO (CPF_FUNCIONARIO, ATRIBUICAO)
VALUES ('12345678901', 'Administrador CEFER')
ON CONFLICT (CPF_FUNCIONARIO, ATRIBUICAO) DO NOTHING;

-- Create user account with hashed password (password: teste123)
-- Using hash_password function to generate bcrypt hash
INSERT INTO USUARIO_SENHA (CPF_PESSOA, SENHA_HASH, DATA_CRIACAO, BLOQUEADO, TENTATIVAS_LOGIN)
VALUES (
    '12345678901',
    hash_password('teste123'),
    CURRENT_TIMESTAMP,
    FALSE,
    0
)
ON CONFLICT (CPF_PESSOA) DO UPDATE
SET SENHA_HASH = hash_password('teste123'),
    DATA_ULTIMA_ALTERACAO = CURRENT_TIMESTAMP,
    BLOQUEADO = FALSE,
    TENTATIVAS_LOGIN = 0;
